# pull official base image
FROM python:3.8.0-alpine

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update gcc python3-dev musl-dev
RUN apk add --no-cache mariadb-dev build-base
RUN apk add jpeg-dev zlib-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copy project and entrypoint
#COPY . /usr/src/app/
# In dev workflow, we only mount

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/scripts/entrypoint.dev"]