#!/bin/bash

# Run these manually after spinning up the prod container
# docker-compose -f docker-compose.prod.yml up -d --build
# docker-compose -f docker-compose.prod.yml exec web python manage.py migrate --noinput
# docker-compose -f docker-compose.prod.yml exec web python manage.py collectstatic --no-input --clear

# Dev:
# docker-compose -f docker-compose.dev.yml up --build

# Prod:
# docker-compose -f docker-compose.prod.yml up --build